config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get :about, to: 'pages#about'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {registrations: 'registrations'}

  resources :users, only: [:show]

  resources :cameras, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews,  only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
   <nav class="navbar navbar-default navbar-static-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">ShareCamera</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <%= link_to "ShareCamera", root_path, class: "navbar-brand" %>
       </div>
       <ul class="nav navbar-nav">
         <li><%= link_to "サービスについて知る", about_path %></li>
       </ul>
       <div id="navbar" class="navbar-collapse collapse">
         <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "キーワード", class: "form-control" %>
          </div>
         <% end %>

         <ul class="nav navbar-nav navbar-right">
           <% if (!user_signed_in?) %>
             <li><%= link_to "ログイン", new_user_session_path %></li>
             <li><%= link_to "無料登録", new_user_registration_path %></li>
           <% else %>
           <li>
             <button class="btn btn-form btn-small">
        　       　<%= link_to "Camera登録", new_camera_path, style: "color: white; text-decoration: none;" %>
        　   </button>
           </li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                      role="button" aria-haspopup="true" aria-expanded="false">

            <%= current_user.fullname %> <span class="caret"></span>
            </a>
             <ul class="dropdown-menu">
　　　　　　　　　<li><%= link_to "登録中Camera", cameras_path %></li>
                <li><%= link_to "貸したCamera", your_reservations_path %></li>
                <li><%= link_to "借りたCamera", your_trips_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "ユーザー編集", edit_user_registration_path %></li>
                <li>
                  <div class="text-center">
                    <%= button_to "ログアウト", destroy_user_session_path, method: :delete %>
                  </div>
                </li>
             </ul>
           </li>
           <% end %>
         </ul>

       </div>
     </div>
   </nav>