config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get :about, to: 'pages#about'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {registrations: 'registrations'}

  resources :users, only: [:show]

  resources :cameras, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews,  only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :camera
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    camera = Camera.find(params[:camera_id])

    if current_user == camera.user
      flash[:alert] = "Share予約できていません!"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = (end_date - start_date).to_i + 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.camera = camera
      @reservation.price = camera.price
      @reservation.total = camera.price * days
      @reservation.save

      flash[:notice] = "Share予約できました!"
    end
    redirect_to camera
  end

  def your_trips
    @trips = current_user.reservations.order(start_date: :asc)
  end

  def your_reservations
    @cameras = current_user.cameras
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end
end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span> ¥<%= @camera.price %>（1日分）</span>
    <span class="pull-right"></span>
  </div>
  <div class="panel-body">
    <%= form_for([@camera, @camera.reservations.new]) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <label>利用可能日</label>
          <%= f.text_field :start_date, readonly: true, placeholder: "開始日", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
          <label>　</label>
          <%= f.text_field :end_date, readonly: true, placeholder: "終了日", class: "form-control datepicker", disabled: true %>
        </div>
      </div>

      <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>価格</td>
              <td class="text-right">¥<%= @camera.price %></td>
            </tr>
            <tr>
              <td>日数</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">合計</td>
              <td class="text-right">¥<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>

      <%= f.submit "予約", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
    <% end %>
  </div>
</div>


<script>

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_camera_path(@camera) %>',
      dateTyp: 'json',
      success: function(data) {

        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_end_date').datepicker("option", "minDate", selected);
            $('#reservation_end_date').attr("disabled", false);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_camera_path(@camera) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @camera.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });

          }
        });

        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_camera_path(@camera) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @camera.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });
          }
        });
      }
    });
  });
</script>

app/views/reservations/_sidebar_list.html.erb
<div class="col-md-3">
  <ul class="sidebar-list">
    <li class="sidebar-item"><%= link_to "登録中Camera", cameras_path, class: "sidebar-link active" %></li>
    <li class="sidebar-item"><%= link_to "貸したCamera", your_reservations_path, class: "sidebar-link active" %></li>
    <li class="sidebar-item"><%= link_to "借りたCamera", your_trips_path, class: "sidebar-link active" %></li>
  </ul>
</div>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <%= render "sidebar_list" %>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        貸したCamera
      </div>
      <div class="panel-body"><br/><br/>

        <% @cameras.each do |camera| %>
            <% camera.reservations.each do |reservation| %>
                <div class="row">
                  <div class="col-md-2">
                    <%= reservation.start_date.strftime('%Y年%-m月%-d日') %>
                    <span>
                      <%= link_to user_path(reservation.user) do %>
                        <h6><%= reservation.user.fullname %></h6>
                      <% end %>
                    </span>
                  </div>
                  <div class="col-md-2">
                    <%= link_to camera_path(reservation.camera) do %>
                        <%= image_tag reservation.camera.cover_photo(:thumb) %>
                    <% end %>
                  </div>
                  <div class="col-md-5">
                    <%= link_to reservation.camera.listing_name, camera_path(reservation.camera) %><br/><br/>
                  </div>
                </div><br/>
                <hr/>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
  <%= render "sidebar_list" %>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        借りたCamera
      </div>
      <div class="panel-body"><br/><br/>

        <% @trips.each do |trip| %>
          <div class="row">
            <div class="col-md-2">
              <%= trip.start_date.strftime('%Y年%-m月%-d日') %><br/><br/>
              <span>
                <%= link_to user_path(trip.camera.user) do %>
                  <h6><%= trip.camera.user.fullname %></h6>
                <% end %>
              </span>
            </div>
            <div class="col-md-2">
              <%= link_to camera_path(trip.camera) do %>
                <%= image_tag trip.camera.cover_photo(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-5">
              <%= link_to trip.camera.listing_name, camera_path(trip.camera) %>
            </div>
          </div><br/>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>