config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get :about, to: 'pages#about'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {registrations: 'registrations'}

  resources :users, only: [:show]

  resources :cameras, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews,  only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/camera.rb
class Camera < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :camera_type, presence: true
  validates :company_type, presence: true
  validates :use_history, presence: true

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_camera, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @cameras = current_user.cameras
  end

  def new
    @camera = current_user.cameras.build
  end

  def create
    @camera = current_user.cameras.build(camera_params)
    if @camera.save
      redirect_to listing_camera_path(@camera), notice: "登録しました！"
    else
      flash[:alert] = "登録できていません！"
      render :new
    end
  end

  def show
    @photos = @camera.photos
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @camera.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params = camera_params
    new_params = camera_params.merge(active: true) if is_ready_camera

    if @camera.update(camera_params)
      flash[:notice] = "保存しました！"
    else
      flash[:alert] = "保存できていません！"
    end
    redirect_back(fallback_location: request.referer)
  end


  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @camera.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @camera)
    }

    render json: output
  end

  def your_trips
    @trips = current_user.reservations.order(start_date: :asc)
  end

  def your_reservations
    @cameras = current_user.cameras
  end


  private

    def is_conflict(start_date, end_date, camera)
      check = camera.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_camera
      @camera = Camera.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @camera.user_id
    end

    def is_ready_camera
      !@camera.active && !@camera.price.blank? && !@camera.listing_name.blank? && !@camera.photos.blank? && !@camera.address.blank?
    end

    def camera_params
      params.require(:camera).permit(:camera_type, :company_type, :use_history, :condition, :listing_name, :summary, :address, :is_camera_case, :is_camera_leg, :is_light, :price, :active, :latitude, :longitude)
    end
end

app/views/cameras/_camera_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "登録中Camera", listing_camera_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "レンタル料金", pricing_camera_path, class: "sidebar-link active" %>
    <% if !@camera.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Camera紹介", description_camera_path, class: "sidebar-link active" %>
    <% if !@camera.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "写真", photo_upload_camera_path, class: "sidebar-link active" %>
    <% if !@camera.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "補助機材", amenities_camera_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "受取場所", location_camera_path, class: "sidebar-link active" %>
    <% if !@camera.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@camera.active && !@camera.price.blank? && !@camera.listing_name.blank? && !@camera.photos.blank? && !@camera.address.blank? %>

<%= form_for @camera do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "公開する", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/cameras/_cameras_list.html.erb
<% @cameras.each do |camera| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag camera.cover_photo(:medium) %>
        </div>
        <div class="panel-body">
          <%= link_to camera.listing_name, camera %><br/>
          ¥<%= camera.price %> - <%= camera.camera_type %> - <%= camera.company_type %>
          <div id="star_<%= camera.id %>"></div>
        </div>
      </div>
    </div>
<% end %>

app/views/cameras/_register_camera.html.erb
<div class="panel-body">
  <div class="container">

    <%= form_for @camera do |f| %>
      <div class="row"><br/><br/>
        <div class="col-md-3 select text-center">
          <div class="form-group">
            <label>Cameraタイプ</label>
            <%= f.select :camera_type, [["一眼レフ", "一眼レフ"], ["ミラーレス", "ミラーレス"], ["GoPro", "GoPro"]],
                          id: "camera_type", prompt: "選択", class: "form-control" %>
          </div>
        </div>

        <div class="col-md-3 select text-center">
          <div class="form-group">
            <label>メーカー</label>
            <%= f.select :company_type, [["Canon", "Canon"], ["Nikon", "Nikon"], ["SONY", "SONY"], ["FUJIFILM", "FUJIFILM"], ["OLYMPUS", "OLYMPUS"]],
                          id: "company_type", prompt: "選択", class: "form-control" %>
          </div>
        </div>

        <div class="col-md-3 select text-center">
          <div class="form-group">
            <label>使用歴</label>
            <%= f.select :use_history, [["1年未満", "1年未満"], ["1~2年", "1~2年"], ["2~3年", "2~3年"], ["3年以上", "3年以上"]],
                          id: "use_history", prompt: "選択", class: "form-control" %>
          </div>
        </div>

        <div class="col-md-3 select text-center">
          <div class="form-group">
            <label>Camera状態</label>
            <%= f.select :condition, [["ほぼ新品", "ほぼ新品"], ["問題なし", "問題なし"], ["一部不具合", "一部不具合"], ["故障あり", "故障あり"]],
                          id: "condition", prompt: "選択", class: "form-control" %>
          </div>
        </div>

      </div><br/><br/>
      <div class="text-center">
        <div><%= f.submit "登録", class: "btn btn-normal" %></div><br/>
      </div>
    <% end %>
  </div>
</div>

app/views/cameras/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'camera_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        補助機材
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @camera do |f| %>
            <br/><br/>

            <div class="row form-group text-center">
              <div class="col-md-4">
                <%= f.check_box :is_camera_case %> Cameraケース
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_camera_leg %> 三脚
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_light %> 撮影ライト
              </div>
            </div>

          </div>
          <br/><br/>

          <div class="text-center">
            <%= f.submit "保存", class: "btn btn-form" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cameras/create.html.erb
<h1>camera#create</h1>
<p>Find me in app/views/camera/create.html.erb</p>

app/views/cameras/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'camera_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Camera紹介
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @camera do |f| %>

            <div class="row">
              <div class="form-group"><br/>
                <label>タイトル</label>
                <%= f.text_field :listing_name, placeholder: "タイトルを入力してください", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group"><br/>
                <label>メッセージ</label>
                <%= f.text_area :summary, rows: 5, placeholder: "あなたの魅力を伝えよう！", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center"><br/>
              <%= f.submit "保存", class: "btn btn-form" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cameras/index.html.erb
<div class="row">
  <%= render "reservations/sidebar_list" %>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        登録中Camera
      </div>
      <div class="panel-body"><br/><br/>

        <% @cameras.each do |camera| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag camera.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= camera.listing_name %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "編集", listing_camera_path(camera), class: "btn btn-form" %>
            </div>
          </div><br/>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cameras/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'camera_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        登録中Camera
      </div>
        <%= render 'register_camera' %>
    </div>
  </div>
</div>

app/views/cameras/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'camera_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        受取場所
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @camera do |f| %>

            <div class="row">
              <div class="form-group"><br/><br/>
                <label>住所</label>
                <%= f.text_field :address, placeholder: "受取できる住所を入力してください", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center"><br/><br/>
              <%= f.submit "保存", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

app/views/cameras/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    登録するCamera
  </div>
  <%= render 'cameras/register_camera' %>
</div>

app/views/cameras/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'camera_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        写真
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @camera, url: camera_photos_path(@camera), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group"><br/>
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> 写真を選ぶ
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center"><br/>
                  <%= f.submit "追加", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cameras/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'camera_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        レンタル料金
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @camera do |f| %>

            <div class="row">
              <div class="form-group"><br/><br/>
                <label>料金</label>
                <%= f.text_field :price, placeholder: "例) 1000", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center"><br/><br/>
              <%= f.submit "保存", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cameras/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @camera.listing_name %></h1>
        <%= @camera.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= gravatar_for @camera.user %><br/><br/>
        <%= @camera.user.fullname %>
      </div>
    </div>
    <hr/>

    <!-- camera Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-camera fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-copyright fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-clock-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-exclamation-circle fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @camera.camera_type %></div>
        <div class="col-md-3"><%= @camera.company_type %></div>
        <div class="col-md-3"><%= @camera.use_history %></div>
        <div class="col-md-3"><%= @camera.condition %></div>
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>登録者からのメッセージ</h3>
        <p><%= @camera.summary %></p>
      </div>
    </div>
    <hr/>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3"><br/>
        <h4>補助機材</h4>
      </div>

      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@camera.is_camera_case %>">Cameraケース</li>
              <li class="<%= 'text-line-through' if !@camera.is_camera_leg %>">三脚</li>
              <li class="<%= 'text-line-through' if !@camera.is_light %>">撮影ライト</li>
            </ul>
          </div>
        </div>
      </div>

    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row">
      <div id='map'></div>

        <style>#map{ width: 100%;height: 400px;}</style>

        <script>
          let map
            function initMap(){
              geocoder = new google.maps.Geocoder()
              var location = {lat: <%= @camera.latitude %>, lng: <%= @camera.longitude %>};
              map = new google.maps.Map(document.getElementById('map'), {
                center: location,
                zoom: 12,
              });

              marker = new google.maps.Marker({
                position:  location,
                map: map
              });
            }

            let geocoder
              function codeAddress(){
                let inputAddress = document.getElementById('address').value;
                geocoder.geocode( { 'address': inputAddress}, function(results, status) {
                  if (status == 'OK') {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                      map: map,
                      position: results[0].geometry.location
                    });
                  } else {
                    alert('該当する結果がありませんでした：' + status);
                  }
                });
              }
            </script>

            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQggixzes7XwzGsniZ7xRDB9y-ZjSfH-w&callback=initMap" async defer></script>
          </div>
          <hr/>
        </div>

  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservations/form' %>
  </div>
</div>

app/views/cameras/update.html.erb
<h1>camera#update</h1>
<p>Find me in app/views/camera/update.html.erb</p>