config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get :about, to: 'pages#about'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {registrations: 'registrations'}

  resources :users, only: [:show]

  resources :cameras, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews,  only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :camera

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @camera = Camera.find(params[:camera_id])

    if params[:images]
      params[:images].each do |img|
        @camera.photos.create(image: img)
      end

      @photos = @camera.photos
      redirect_back(fallback_location: request.referer, notice: "アップロードできました！")
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @camera = @photo.camera

    @photo.destroy
    @photos = Photo.where(camera_id: @camera.id)

    respond_to :js
  end
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to camera_photo_path(photo.camera_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")
<% if @camera.photos.blank? %>
  $('#photo_check').hide();
<% end %>

<% if !@camera.active && !@camera.price.blank? && !@camera.listing_name.blank? && !@camera.photos.blank? && !@camera.address.blank? %>
    $('#publish_button').attr('disabled', false);
<% else %>
    $('#publish_button').attr('disabled', true);
<% end %>